#!C:\Users\albin\Desktop\End2End_ML_Project\End-to-End-Machine-Learning-Project-with-MlFlow\mlproj\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
